export const candidateContent = {
  candidateFolk: {
    name: "Anders Folk",
    party: "TK",
    website: "https://www.andersfolk.com/",
    city: "TK",
    neighborhood: "TK",
    occupation: "TK",
    age: "TK",
    bio: "A few paragraphs describing the candidate’s background, to be shown at the top of the candidate’s profile page. Note: if the text includes more than one paragraph, just write {newParagraph} in between to split it up. Do not separate the paragraphs with line breaks.",
    quote1: "TK",
    quote2: "TK",
    quote3: "TK",
    quote4: "TK",
    quote5: "TK",
    quizResponse1: "",
    quizResponse2: "",
    quizResponse3: "",
    quizResponse4: "",
    quizResponse5: "",
    quizResponse6: "",
    quizResponse7: "",
    quizResponse8: "",
    quizResponse9: "",
    quizResponse10: "",
    quizResponse11: "",
  },
  candidateNguyen: {
    name: "Hao Nguyen",
    party: "TK",
    website: "https://hao4hennepin.com/",
    neighborhood: "TK",
    occupation: "TK",
    age: "TK",
    bio: "A few paragraphs describing the candidate’s background, to be shown at the top of the candidate’s profile page. Note: if the text includes more than one paragraph, just write {newParagraph} in between to split it up. Do not separate the paragraphs with line breaks.",
    quote1: "TK",
    quote2: "TK",
    quote3: "TK",
    quote4: "TK",
    quote5: "TK",
    quizResponse1: "",
    quizResponse2: "",
    quizResponse3: "",
    quizResponse4: "",
    quizResponse5: "",
    quizResponse6: "",
    quizResponse7: "",
    quizResponse8: "",
    quizResponse9: "",
    quizResponse10: "",
    quizResponse11: "",
  },
  candidateKrenz: {
    name: "Diane Krenz",
    party: "TK",
    website: "https://www.dianekrenz.com/",
    neighborhood: "TK",
    occupation: "TK",
    age: "TK",
    bio: "A few paragraphs describing the candidate’s background, to be shown at the top of the candidate’s profile page. Note: if the text includes more than one paragraph, just write {newParagraph} in between to split it up. Do not separate the paragraphs with line breaks.",
    quote1: "TK",
    quote2: "TK",
    quote3: "TK",
    quote4: "TK",
    quote5: "TK",
    quizResponse1: "",
    quizResponse2: "",
    quizResponse3: "",
    quizResponse4: "",
    quizResponse5: "",
    quizResponse6: "",
    quizResponse7: "",
    quizResponse8: "",
    quizResponse9: "",
    quizResponse10: "",
    quizResponse11: "",
  },
  candidatePelikan: {
    name: "Matt Pelikan",
    party: "TK",
    website: "https://mattpelikan.com/",
    neighborhood: "TK",
    occupation: "TK",
    age: "TK",
    bio: "A few paragraphs describing the candidate’s background, to be shown at the top of the candidate’s profile page. Note: if the text includes more than one paragraph, just write {newParagraph} in between to split it up. Do not separate the paragraphs with line breaks.",
    quote1: "TK",
    quote2: "TK",
    quote3: "TK",
    quote4: "TK",
    quote5: "TK",
    quizResponse1: "",
    quizResponse2: "",
    quizResponse3: "",
    quizResponse4: "",
    quizResponse5: "",
    quizResponse6: "",
    quizResponse7: "",
    quizResponse8: "",
    quizResponse9: "",
    quizResponse10: "",
    quizResponse11: "",
  },
  candidateFrazier: {
    name: "Cedrick Frazier",
    party: "TK",
    website: "https://www.cedrickfrazier.org/",
    neighborhood: "TK",
    occupation: "TK",
    age: "TK",
    bio: "A few paragraphs describing the candidate’s background, to be shown at the top of the candidate’s profile page. Note: if the text includes more than one paragraph, just write {newParagraph} in between to split it up. Do not separate the paragraphs with line breaks.",
    quote1: "TK",
    quote2: "TK",
    quote3: "TK",
    quote4: "TK",
    quote5: "TK",
    quizResponse1: "",
    quizResponse2: "",
    quizResponse3: "",
    quizResponse4: "",
    quizResponse5: "",
    quizResponse6: "",
    quizResponse7: "",
    quizResponse8: "",
    quizResponse9: "",
    quizResponse10: "",
    quizResponse11: "",
  },
  candidateMoriaty: {
    name: "Mary Moriaty",
    party: "TK",
    website: "TK",
    neighborhood: "TK",
    occupation: "TK",
    age: "TK",
    bio: "A few paragraphs describing the candidate’s background, to be shown at the top of the candidate’s profile page. Note: if the text includes more than one paragraph, just write {newParagraph} in between to split it up. Do not separate the paragraphs with line breaks.",
    quote1: "TK",
    quote2: "TK",
    quote3: "TK",
    quote4: "TK",
    quote5: "TK",
    quizResponse1: "",
    quizResponse2: "",
    quizResponse3: "",
    quizResponse4: "",
    quizResponse5: "",
    quizResponse6: "",
    quizResponse7: "",
    quizResponse8: "",
    quizResponse9: "",
    quizResponse10: "",
    quizResponse11: "",
  },
};
