export const candidateContent = {
  candidateFolk: {
    name: "Anders Folk",
    website: "https://www.andersfolk.com/",
    city: "Minneapolis",
    occupation: "Attorney",
    age: "49",
    bio: "Anders Folk grew up in Hopkins and attended the University of Minnesota, where he earned his undergraduate degree and completed two years of law school before joining the United States Marine Corps. He returned to Minnesota to finish law school and briefly worked for then-Hennepin County Amy Klobuchar, but was activated by the military months after the September 11 attacks.{newParagraph}As an active-duty service member, Folk worked as a criminal defense attorney within the Marine Corps, and later served as a military prosecutor. He did not see combat. He came back to Minnesota and was hired as a federal prosecutor in the U.S. Attorney’s Office, where he spent five years investigating and charging cases involving gangs, organized crime, terrorism, fraud and violent crimes, among others.{newParagraph}Folk then went into private practice in 2011 for nearly eight years, but later returned to the U.S. Attorney’s Office and was appointed the acting U.S. Attorney in 2021 by President Joe Biden. He led the office during the civil trial of Derek Chauvin and three other Minneapolis police officers who murdered George Floyd in 2020. He stepped down from that role, and moved to Washington D.C. to work as senior counsel on litigation and policy matters for Deputy U.S. Attorney General Lisa Monaco, advising Monaco and U.S. Attorney General Merrick Garland.{newParagraph}Folk told Sahan Journal he joined the race because Hennepin County needs an experienced prosecutor with a “public safety first mindset.” He is endorsed by former U.S. Attorney for Minnesota Andy Luger, as well as Minneapolis Mayor Jacob Frey, three Minneapolis City Council members, and former Hennepin County judges Peter Cahill and Martha Holton Dimick.{newParagraph}Sahan Journal asked the county attorney candidates several questions about why they’re running for the office, and their priorities for the post. Read Folk’s responses in his own words below.",
    quote1:
      "Because Hennepin County deserves an experienced prosecutor and leader who will work every day for everyone in Hennepin County.{newParagraph}Because we need a change of direction at the Hennepin County Attorney’s Office and because I believe in and am committed to public service and public safety.{newParagraph}The Hennepin County Attorney’s Office needs an experienced prosecutor and proven leader to run this office. As a U.S. Marine, a former acting U.S. attorney and career federal prosecutor, I have the leadership record and courtroom experience that no other candidate in this race can claim.{newParagraph}Everyone in Hennepin County deserves to be safe, to receive equal justice, and to be treated with dignity, no matter who you are, what you look like, or where you live. I have the experience to make this happen.{newParagraph}I am a lifelong Minnesotan, a career federal prosecutor, and a former senior official in the U.S. Department of Justice during the Biden administration.{newParagraph}While leading the U.S. Attorney's Office, I signed the indictment charging Derek Chauvin with violating George Floyd's civil rights.{newParagraph}Over two decades of legal and public service experience, I have handled complex federal cases involving violent crime, domestic terrorism, public corruption, large-scale fraud, and civil rights violations. During law school, I joined the Marine Corps, and I worked at the Hennepin County Attorney’s office in the juvenile division under Amy Klobuchar. My first job out of law school was working as a military lawyer as a prosecutor and defense lawyer before going on to serve as an assistant U.S. attorney in Minnesota.{newParagraph}I am ready to lead this office forward with experience, compassion and humility on day one.",
    quote2:
      "Please go to www.andersfolk.com for a full list of my priorities and my plan for 100 Days of Action. You can learn more about my priorities here and check out my 100 Days of Action plan to get to work on day one here.{newParagraph}My priorities are built on four key ideas.{newParagraph}First, the Hennepin County Attorney’s Office will create a Task Force to investigate and prosecute violations of Minnesota law by federal agents during Operation Metro Surge.{newParagraph}Second, the office will strategically focus on violent and repeat offenders to ensure every community in Hennepin County feels safe and protected.{newParagraph}Third, we will be data-driven in how we intervene to prevent harm and keep communities safe, especially the most vulnerable among us. We will be fair in how we address juvenile justice and crime victims.{newParagraph}And fourth, we will be collaborative and lead our many public safety partners across Hennepin County, including police, educators, faith leaders, mayors, city council members, and community leaders.",
    quote3:
      "My approach to leadership, collaboration, and policymaking will be fundamentally different from day one.{newParagraph}First, our many public safety partners across Hennepin County, including police, educators, faith leaders, mayors, city council members, and community leaders will have a seat at the table and will help us focus our resources.{newParagraph}Second, we will lift up the voices of crime victims and ensure they are heard. We are creating a Hennepin County Crime Victims bill of rights to ensure our crime victims and their families are heard.{newParagraph}Third, we will hold people accountable and ensure repeat and violent offenders are not simply released back to the community without consequence. Our priority is to protect the people of Hennepin County.",
    quote4:
      "The County Attorney’s Office has a crucial role to play in delivering justice for everyone and helping bridge racial disparities, most immediately when it comes to combating and preventing crime.{newParagraph}Hennepin County accounts for about 22% of the state's population but roughly 44% of its violent crime.{newParagraph}Across Minnesota, the rate of criminal offenses against Black residents is about 9.5 times higher than what is committed against the lowest group rate.{newParagraph}Homicide rates for Black Minnesotans and American Indian Minnesotans are each more than 10 times the rate for white Minnesotans.{newParagraph}The communities most impacted by crime are communities of color -- and one way to combat crime is to prevent it from occurring in the first place. I am committed to expanding our county’s use of prevention and intervention work to disrupt cycles of violence before they escalate.{newParagraph}And as a federal prosecutor, I have worked side-by-side with city and county leaders to support successful prevention and intervention techniques like Group Violence Intervention that focus on strategic enforcement. I am excited at the opportunity to expand that work.",
    quote5:
      "I think the first and best step will be to conduct listening sessions with members of the public who receive services and to hear first-hand how the office can best improve services and reduce disparities in how the County Attorney provides services. I am committed to ensuring the County Attorney’s office is accessible and working for our most vulnerable and often unheard communities.",
    quizResponse1:
      "1 | “My general practice would be to continue every case brought by the current county attorney that can be proven beyond a reasonable doubt.{newParagraph}ICE agents and federal officers have created fear and chaos across Minnesota, with Hennepin County at the center. The rule of law matters today more than ever, and I am committed to ensuring it is applied equally and fairly. As Hennepin County attorney, I will pursue accountability for all violations of law by federal agents during Operation Metro Surge.{newParagraph}Under the current administration, the Department of Justice has been weaponized against Minnesota. Grand juries and professional prosecutors have been used across the United States to intimidate and settle personal scores, court orders are ignored, and our Constitution is under attack. As a result, important cases have been dismissed and an exodus of career prosecutors have felt compelled by their conscience to leave the office.{newParagraph}Now, the Hennepin County Attorney's Office will need to step into the void created by the loss of these federal prosecutors to ensure we are delivering justice in Hennepin County. I am ready and have the experience to bring people together and lead that effort immediately.”",
    quizResponse2: "1 |",
    quizResponse3: "1 |",
    quizResponse4:
      "4 | “The options as drafted are both over and underinclusive.{newParagraph}The Hennepin County attorney has an obligation to gather evidence and victim accounts regarding the conduct of law enforcement officers and to bring charges when they can be proven beyond a reasonable doubt.”",
    quizResponse5:
      "2 | “There will be instances that require more than slight enforcement.{newParagraph}Violent offenders and those involved in premeditated violence require consequences that both prevent the juvenile from putting others at risk and that provides real opportunity to rehabilitate and educate the juvenile, with a goal of eliminating future offenses.”",
    quizResponse6:
      "3 | “There is no one-size-fits-all approach to juvenile justice. We must always focus on providing juveniles with rehabilitation and education to prevent future offenses. As noted above, consequences for juvenile offenders should increase for repeat offenders. Violent offenders and those involved in premeditated violence require consequences that both prevent the juvenile from putting others at risk and that provides real opportunity to rehabilitate and educate the juvenile, with a goal of eliminating future offenses{newParagraph}As part of this approach, I am committed to working with service providers to improve and expand where possible our diversion and restorative justice initiatives.”",
    quizResponse7:
      "3 | “Leadership requires constant collaboration. The Hennepin County attorney leads the largest public law office in Minnesota and has the opportunity -- and responsibility -- to bring together public safety partners and community leaders around a shared vision for safety. As Hennepin County attorney, I will lead from the front and work with stakeholders to shape policies and strategies that work. That commitment to transparency and accountability will help ensure that more residents and community members see the system operating with fairness, openness, honesty, and integrity -- which in turn strengthens public safety.{newParagraph}Building and maintaining partnerships with law enforcement offices and agencies across Hennepin County are a critical part of any roadmap for public safety. As Hennepin County attorney, I will be committed to working with our law enforcement partners and making clear that the Hennepin County Attorney's Office will do its job to ensure public safety and we expect our law enforcement partners to do their job.”",
    quizResponse8:
      "4 | “This policy debate is a good example of the leadership failures we have seen from the current county attorney’s approach. Law enforcement partners, including the sheriff and police chiefs, were blindsided by the policy and were given no opportunity to provide any input before the policy was implemented. That's not how a community-first leader builds trust.{newParagraph}I am committed to implementing a traffic stop policy that is constitutional, consistent with Minnesota law, and provides law enforcement officers to use their discretion, while never allowing the individual characteristics of driver or passenger to be the basis for a stop or an arrest.”",
    quizResponse9:
      "2 | “The governor was right to intervene in this case because the county attorney failed to appropriately handle this matter. The governor’s authority needs to be used sparingly and only in the most egregious cases. I believe this case met that threshold.”",
    quizResponse10: "2 |",
    quizResponse11: "1 |",
  },
  candidateNguyen: {
    name: "Hao Nguyen",
    website: "https://hao4hennepin.com/",
    city: "Minneapolis",
    occupation: "Senior Assistant County Attorney",
    age: "43",
    bio: "Hao Nguyen, his mother and two brothers fled the Vietnam War and lived in a refugee camp in the Philippines for two years before immigrating to the United States. He grew up in a trailer park in St. Cloud, as his mother worked at a meat processing plant. Nguyen and his brothers attended school as English-as Second-Language students.{newParagraph}Nguyen attended St. Cloud State University and worked as a correctional officer at the Stearns County jail during college. Nguyen worked for the St. Cloud Police Department for a year before joining the Stearns County Sheriff’s Office as a deputy.{newParagraph}Nguyen told Sahan Journal his experience testifying at trials as a law enforcement officer compelled him to pursue a career as a lawyer. He attended the Mitchell Hamline School of Law while working as a deputy, commuting from St. Cloud to St. Paul during his first three years of law school. He quit his job to become a full-time law student in 2009, and graduated a year later. Nguyen clerked in the Hennepin County Attorney’s Office for three years, where he focused on juvenile prosecutions. {newParagraph}He returned to St. Cloud to work as a prosecutor, working on misdemeanors and domestic assault and drunk driving cases. He was hired by the Ramsey County Attorney’s Office in 2014, and has worked there since, eventually becoming director of the office’s trials division.{newParagraph}Nguyen is endorsed by state senators Foung Hawj and Susan Pha, Hennepin County Sheriff Dawanna Witt, Ramsey County Attorney John Choi, St. Paul Mayor Kaohly Her and several other local officials.{newParagraph}Sahan Journal asked the county attorney candidates several questions about why they’re running for the office, and their priorities for the post. Read Nguyen’s responses in his own words below.",
    quote1:
      "We are at a crossroads: Hennepin County still faces high crime rates, there’s currently low trust in the county attorney's office, and we need to find justice for victims of Operation Metro Surge. In Ramsey County, where I’m director of the trials division, we’ve lowered gun violence, reduced auto theft, cut racial disparities, and more, all through hard conversations and collaboration. We are investigating federal agents with local law enforcement. We need this experienced, collaborative, innovative, transparent leadership desperately; I know I can provide it.{newParagraph}I am a refugee. Growing up in a trailer park in St. Cloud, MN, my mom had PTSD from the Vietnam War and my brother had schizophrenia. I know what it’s like to have nothing – and to be racially profiled. These lived experiences have helped me have empathy for people who commit crimes and also know how critical safety is for everyone in Hennepin County. I have dedicated my life to public service: first as a corrections officer, then as a police officer, and now as a prosecutor in a county attorney’s office. I am the most qualified candidate for Hennepin County attorney.",
    quote2:
      "Everyone in Hennepin County knows someone who's been a victim of crime these last four years -- if it hasn't happened to them. Car thefts in Minneapolis are up 24% since this time in 2025. I'm hearing that voters want their county attorney to do all they can to keep them safe, and they want to know people are being treated fairly. I will partner with law enforcement and transfer the trauma-informed victim services and diversion practices we're using in Ramsey County to help keep everyone in Hennepin County safe, and protect everyone’s rights and work to address the root causes of crime.",
    quote3:
      "The current Hennepin County attorney has made some good changes, such as hiring social workers to support truancy reduction efforts and developing focused deterrence strategies. However, their manner of making decisions and instituting changes without sufficient input and support from the community and stakeholders has hurt the standing and effectiveness of the office.{newParagraph}I've been a prosecutor for 16 years and for the past 7 have led the trial division in the Ramsey County Attorney’s Office. I supervise prosecutors, manage budgets, hire and train attorneys. I worked nights as a correctional officer to put myself through college; there I learned that every one person, inmate or not, deserves to be treated with dignity and respect.{newParagraph}My years as a sworn police officer and deputy sheriff give me credibility with law enforcement — credibility that I use to work with them to make good reforms. But let me be clear, collaboration doesn’t mean deference: and when officers violate our trust, I have no problem holding them accountable.{newParagraph}We’ve gotten real results in Ramsey County through hard conversations and focused collaboration.{newParagraph}We have:{newParagraph}- Cut racial disparities in traffic stops by more than half.{newParagraph}- Reduced carjacking and auto theft to nation-leading levels.{newParagraph}- Utilizing restorative justice practices we’ve reduced youth recidivism.{newParagraph}- And we’ve brought gun violence down to an all time low.{newParagraph}I’ve stood up to sex traffickers, abusive employers, and federal government overreach. I'm currently leading a team investigating federal officer abuses and I will not back down until we get to the truth and see accountability.{newParagraph}This is the experience and kind of leadership I’ll bring to the Hennepin County Attorney’s Office on day one.",
    quote4:
      "I believe it is a prosecutor's duty to address social inequity that is impacted by their role. For example, prosecutors should have strong programs for assisting with the sealing of criminal records when appropriate, because those records perpetuate inequities, as well as often being counterproductive generally as a public safety tool. Additionally, to the extent they have the ability to do so, they should provide leadership in addressing issues that lead to involvement in the criminal justice system, such as housing and employment inequities, and supporting changes and programs in the criminal legal system that address underlying issues such as mental health and addiction.",
    quote5:
      "By developing and maintaining a strong relationship with the court, the county attorney can have an impact on these matters. I have done this in Ramsey County and will work to build a strong relationship that will help to bring community concerns to the court that will result in needed changes.",
    quizResponse1: "1 | “I am already leading this work in Ramsey County.”",
    quizResponse2: "1 |",
    quizResponse3: "1 |",
    quizResponse4: "1 |",
    quizResponse5:
      "2 | “We need better placement options for youth. We need local community-based and supported placements. This is something we've worked on in Ramsey County and that I'd like to play a leadership role in Hennepin.”",
    quizResponse6:
      '1 | “I almost answered "case by case approach", but I do believe in an emphasis on rehabilitation and support for youth.”',
    quizResponse7: "3 |",
    quizResponse8:
      "3 | “We've cut disparities in stops in half through a similar policy in Ramsey County. My first step would be to meet with all of the police chiefs and sheriff about it, and work to build support for a policy like we did in Ramsey. Without law enforcement support the disparities will just continue.”",
    quizResponse9: "2 |",
    quizResponse10:
      "4 | “Having not been the decision-maker in this specific case, for many reasons it's not appropriate for me to make a statement.”",
    quizResponse11: "1 |",
  },
  candidateKrenz: {
    name: "Diane Krenz",
    website: "https://www.dianekrenz.com/",
    city: "Minnetonka",
    occupation: "Attorney",
    age: "66",
    bio: "Diane Krenz grew up on a Wisconsin dairy farm close to the Minnesota border, which her family often crossed for shopping and to attend the Minnesota State Fair. She graduated from the University of Wisconsin-Eau Claire and the Mitchell Hamline School of Law. {newParagraph}Krenz worked in the Hennepin County Attorney’s Office for more than 40 years. She started as a law clerk in 1983 under then-county attorney Mike Freeman, and was hired by Freeman as a full-time attorney in 1986 to prosecute juvenile crime. She was moved to adult prosecutions five years later, where she worked for another 10 years before moving onto gang cases.{newParagraph}Krenz started working on property cases in 2007, including burglary and theft, while specializing in repeat offenders who had dozens of prior felonies. A decade later, she transitioned to the office’s white collar crimes division, which included large-scale embezzlements and fraud involving taxes, insurance and public benefits.{newParagraph}Krenz left the office in April 2025 and briefly worked as an independent contractor helping local officials in parts of the state that lack resources to prosecute large financial crimes. Despite retiring earlier this year, Krenz told Sahan Journal she decided to run for county attorney to ensure that the office is properly listening to victims and collaborating with law enforcement to attain justice.{newParagraph}Sahan Journal asked the county attorney candidates several questions about why they’re running for the office, and their priorities for the post. Read Krenz’s responses in her own words below.",
    quote1:
      "I'm running to refocus the office on its core missions. While the criminal justice system always needs to be made better, the current administration has taken reform beyond what makes sense. As a 40 year career Hennepin County prosecutor, I've seen what works and what doesn't. The office is going in the wrong direction and I believe I am in the best position to return the office to increasing public safety and seeing justice done.",
    quote2:
      "Prosecute violent and repeat offenders, imposing proper Sentencing Guideline sentences when appropriate. Re-establish working relationships with all law enforcement agencies. Make certain that victims of criminal cases have the information and input required under M.S. Stat. 611A, which will revitalize the office's victim/witness division. Establish a community engagement team that actually works with the community.",
    quote3:
      "I will change all the current county attorney's policies as most of them undermine the mission of the office.",
    quote4:
      "I have seen that a disproportionate number of violent crime victims are racial minorities. It would not be just or fair to ignore that issue. Victims of color should get the same treatment as any other victim. Taking the race of the offender into consideration when charging or resolving cases would be patently unfair to any minority victims. I would require a color blind neutral evaluation of all cases, just as was done during the years while I was in the office.",
    quote5:
      "It's unclear to me to what this is referring. Do you mean in child protection cases? Child support cases? Mental health commitment cases? If you mean those, I don't see a problem with how the system is working.",
    quizResponse1:
      "3 | “I believe it is unethical to commit to prosecuting cases without reviewing the evidence to determine whether the case can be proven beyond a reasonable doubt to a jury.”",
    quizResponse2:
      "1 | “These choices do not clearly explain what I would do. To me, active investigation means working with law enforcement, not leading the investigation. The Hennepin County Attorney's Office isn't an investigative agency. What we do, and I have done for years, is discuss a case with the police, make suggestions and help evaluate evidence before a case is submitted. My administration would continue involvement in that manner.”",
    quizResponse3:
      "1 | “Any person who commits a crime that can be proven beyond a reasonable doubt should be charged. There are specific issues, however, about prosecuting federal law enforcement which need to be considered.”",
    quizResponse4:
      "2 | “None of the choices above accurately reflect my position. The Hennepin County Attorney's Office does not investigate crime. It does, however, offer assistance sometimes by advising local law enforcement and allowing in-office investigators help. It is one thing to direct victims to police for interviews or a person submit evidence to law enforcement; it is quite another to collect the evidence, do interviews, and forward this on to the police. {newParagraph}One of the problems of the county attorney's office completely investigating cases is that subsequently charged defendants can make claims of bias and misconduct which cannot be countered. That is why the office relies on the police to investigate a case and present it to the office. The assigned attorney is at an arm's length and therefore can be more critical of the case. The decision to have the office collect evidence and interview witnesses is misguided.”",
    quizResponse5:
      "2 | “These choices don't reflect how juvenile law works in this state. Minnesota's juvenile delinquency statutes recognize that juveniles under 18 are different from adults and therefore provide different procedures and consequences for children. The intent of these statutes is to protect public safety and rehabilitate the offender. These must be balanced. There is no prison for juveniles. Prison sentences are typically reserved for cases where an offender has been certified for a very serious public safety crime. It can be used when a juvenile on extended juvenile jurisdiction has violated conditions of the stay. What I would not do is continue the current County Attorney's focus on no consequences. Rather, I would apply the public safety portion of the law.”",
    quizResponse6:
      "3 | “Every case, juvenile or adult, has to be dealt with on a case by case basis. Every offender is different. So too is every case. Prosecutors must evaluate what evidence is admissible, if there are issues about witnesses or police action, and what is best for the victim, the defendant and public safety. Addressing violent crime is one of my priorities and in some cases, prison sentences for juveniles will be necessary. As stated in my previous answer, prison sentences are a limited option for juveniles. My policies would always consider public safety in these decisions.”",
    quizResponse7:
      "3 | “That is the closest to my position, however, I would take cases from police officers who have a history of discipline. That decision would depend on many factors, such as what role the officer had in the case or what the officers conduct was. My priority is to heal the relationships with all police departments in Hennepin County as these have been damaged during the current administration. The office is obligated to assist in training the police, working with them to build cases, and not charge cases where the police have violated a suspect's constitutional rights. I would consult with them on policy issues.”",
    quizResponse8:
      "2 | “If the police officers did not violate the suspect's constitutional rights by stopping and searching the vehicle, there is no reason not to charge.”",
    quizResponse9:
      "2 | “I agree with the position of the Minnesota County Attorneys Association, who opposed this action. Governor Walz's action is not recognized in law. Local elected county attorneys best reflect the standards in their jurisdiction and there are statutes that govern how cases are moved to the attorney general's office. However, I do not agree with how Ms. Moriarty handled that case because it was unfair to the victim and her family.”",
    quizResponse10:
      "2 | “Ms. Moriarty treated the victim and her surviving family poorly. The victim had been shot five times in the head by the younger juvenile. The case occurred during Mike Freeman's administration and the office had talked to the family, letting them how the case was going to be handled. Moriarty came in and changed the case's direction with little or no input from the family. She let the family clearly know that she cared more about the offenders than the victim, who was the mother of a baby. That is my first concern. {newParagraph}I also understand probation recommended that the juvenile who shot Ms. McKeever go to prison after his history was reviewed. In my practice and experience, homicide offenders should rarely receive probation. This case is no exception.”",
    quizResponse11:
      "1 | “The premise of these three choices is inaccurate. While there are times the two offices work together, that is relatively rare. The Hennepin County Attorney's Office would rarely have reason to sue the federal government unless it involves a particular case (see Pretti and Good). However, I think it is always beneficial to work with other state executives. The attorney general and some elected county attorneys work together on wage theft and labor trafficking cases. That is a useful collaboration and has increased investigation of those crimes. However, other than certain policy matters, there aren't many reasons to work together on prosecutions as there is little overlap of prosecution work. The civil work of the two offices almost never intersects. When there is an opportunity to work together toward some goals, I would do it.”",
  },
  candidatePelikan: {
    name: "Matt Pelikan",
    website: "https://mattpelikan.com/",
    city: "Minneapolis",
    occupation: "Attorney",
    age: "45",
    bio: "Matt Pelikan grew up in Northfield, where his mother was a mental health professional and his father was a radio producer. He got involved in politics as a teenager at the encouragement of progressive activist neighbors, and was eventually elected DFL precinct chair at 16 years old.{newParagraph}After graduating from St. Olaf College, Pelikan went to work for U.S. Senator Paul Wellstone and then-state senator Mark Dayton, both Democrats. He attended the University of Minnesota School of Law, and went on to clerk for Minnesota Supreme Court Justices Paul Anderson and David Lillehaug. He then began a long career in private practice.{newParagraph}Pelikan, a partner at MADEL PA law firm in Minneapolis, has represented individuals, nonprofits and large companies in cases involving consumer protection, intellectual property and business disputes. Pelikan ran for Minnesota Attorney General in 2018 as the DFL’s endorsed candidate, but lost to Keith Ellison.{newParagraph}Sahan Journal asked the county attorney candidates several questions about why they’re running for the office, and their priorities for the post. Read Pelikan’s responses in his own words below.",
    quote1:
      "I am running because Hennepin County needs a county attorney who can deliver both safety and justice — and who has the independence and legal experience to actually do it.{newParagraph}This community has been through a terrible stretch: violence in our neighborhoods, deep distrust in the justice system, and this winter’s Metro Surge, when federal agents came into our streets and left people harmed, afraid, and still waiting for real accountability. I believe accountability for what happened during Metro Surge is one of the defining legal and moral tests facing the next county attorney.{newParagraph}But accountability is not a slogan. These will be hard cases. They will require judgment, courage, and serious legal skill. I have spent nearly 30 years organizing, litigating, and taking on powerful interests. I have represented people harmed by the powerful, gone to the Minnesota Supreme Court to change the law, and built a career around hard fights where the stakes are real. I am the only reform candidate in this race with the legal experience to manage complicated, high-pressure cases and make accountability more than a promise.{newParagraph}I am also running from outside the political establishment. The established interests that broke trust in this system are not going to be the ones to fix it. Hennepin County needs independent leadership — someone who is not beholden to the same insiders, factions, and failed assumptions that have left too many people feeling unsafe and unheard.{newParagraph}I reject the idea that we have to choose between reform and public safety. We need an office that takes violent crime seriously, protects constitutional rights, treats victims with dignity, works with law enforcement without being captured by it, and applies the law equally no matter who is accused of breaking it.{newParagraph}That is why I am running: to build an office worthy of this moment, rooted in safety, justice, independence, and real accountability.",
    quote2:
      "First, the county attorney’s office must take violent crime seriously. People deserve to feel safe in their homes, neighborhoods, schools, transit stops, and public spaces. That means focusing resources on the cases that cause the most harm, holding violent and repeat offenders accountable, and working with law enforcement, community organizations, public health leaders, schools, and service providers to prevent violence before it happens.{newParagraph}Second, we need real accountability for Metro Surge and for abuses of power wherever they occur. The law must apply equally whether someone is on a street corner, in a boardroom, or wearing a badge. The next county attorney will have to make difficult, legally complex decisions about federal agents and others who harmed our community. That work must be careful, independent, transparent, and strong enough to withstand pressure.{newParagraph}Third, the office must rebuild trust by being fair, transparent, and consistent. Communities need to understand how charging decisions are made. Victims need to be treated with dignity. Defendants must have their rights protected. And the public needs confidence that politics, favoritism, fear, or insider relationships are not driving decisions.{newParagraph}Fourth, I will focus on protecting people from economic harm, including fraud, wage theft, scams targeting seniors, consumer abuse, and exploitation by powerful interests. Public safety is not only about violent crime. It is also about whether people can live their lives without being cheated, threatened, or abused.{newParagraph}Finally, I will make the office itself a stronger, more inclusive, and more effective workplace. The county attorney’s office is a large public institution, and it cannot succeed without the people who do the work every day. That means listening to staff, respecting public workers, recruiting and retaining diverse talent, and building a culture where people are supported, accountable, and focused on the mission.",
    quote3:
      "I will lead in a way that rebuilds the coalition for reform instead of shattering it.{newParagraph}My predecessor raised important issues about racial disparities, youth justice, and the need to think differently about prosecution. Those conversations matter. But reform does not happen by announcement, by faction, or by making enemies out of people who should be allies. It requires a coalition: public defenders, prosecutors, victims, law enforcement, public workers, community organizations, reform advocates, neighborhood leaders, and people directly impacted by the system.{newParagraph}The biggest problem with the current office is not simply one policy or one case. It is that the office lost the trust of too many people it needs in order to succeed. It alienated staff. It strained relationships with law enforcement. It left victims and neighborhoods feeling unheard. And it too often treated disagreement as betrayal rather than as part of the hard work of governing.{newParagraph}I will do that differently.{newParagraph}I believe reform has to be built, not declared. As county attorney, I will bring people to the table before major decisions are made. I will be clear about standards, transparent about priorities, and willing to listen to people who do not already agree with me. I will take violent crime seriously while also protecting constitutional rights, reducing disparities, and pursuing alternatives that actually make communities safer.{newParagraph}The choice is not between going backward and pretending the current approach is working. Hennepin County needs a county attorney who can rebuild trust, restore focus, and make reform durable enough to survive beyond one administration.",
    quote4:
      "Racial and economic disparities show up at nearly every stage of the criminal justice system: who is policed, who is charged, who sits in jail before trial, who has access to treatment or diversion, whose harm is taken seriously, and who has the resources to recover after contact with the system.{newParagraph}As county attorney, I would start from a basic principle: the law must be applied fairly, consistently, and without regard to race, income, neighborhood, or political power. That means taking disparities seriously without pretending that public safety concerns are not real. The communities most harmed by over-policing are often the same communities most harmed by violence, under-protection, and lack of accountability.{newParagraph}I would address these disparities in several ways.{newParagraph}First, I would demand clear, transparent standards for charging and plea decisions so that similarly situated people are treated similarly. Discretion is unavoidable in prosecution, but it should not be invisible or arbitrary.{newParagraph}Second, I would expand and strengthen alternatives to incarceration where they actually promote safety: treatment, restorative approaches, youth interventions, mental health responses, and diversion for lower-level offenses. Poverty, addiction, trauma, and housing instability should not be made worse by unnecessary criminal justice involvement.{newParagraph}Third, I would take seriously the economic drivers of injustice. People should not sit in jail simply because they are poor. Victims should not be ignored because they live in a neighborhood with less political power. And the office should pursue wage theft, fraud, scams targeting seniors, and other forms of exploitation that harm working people and low-income communities.{newParagraph}Fourth, I would rebuild the coalition necessary for durable reform. Reducing disparities requires prosecutors, public defenders, judges, law enforcement, community groups, victims’ advocates, public workers, and directly impacted people to work from a shared commitment to both safety and justice.{newParagraph}The goal is not a system that is simply less punitive. The goal is a system that is more fair, more focused, more effective, and more trusted by the people it serves.",
    quote5:
      "Civil court work is often less visible than criminal prosecution, but it can have enormous consequences for families, workers, taxpayers, and vulnerable residents. The office should approach civil matters with the same commitments to fairness, transparency, and public service.{newParagraph}That means using plain language, improving communication with people who are not lawyers, expanding language access, and making sure people understand what is happening in cases that affect their lives. It also means using discretion wisely in areas like child protection, civil commitments, collections, and county litigation so that poverty, disability, housing instability, or lack of legal representation do not become barriers to justice.{newParagraph}The office should look for ways to resolve civil matters earlier, avoid unnecessary escalation, and reduce practices that punish people simply because they are poor. At the same time, it should be aggressive when civil enforcement can protect the public — against fraud, exploitation, wage theft, scams targeting seniors, and abuses by powerful interests.{newParagraph}Civil practice should reflect the same principle as the rest of the office: government power must be used carefully, fairly, and in service of the public.",
    quizResponse1:
      "1 | “Accountability for Operation Metro Surge is one of the defining legal and moral tests facing the next county attorney. When agents used force in our community, harmed our neighbors, and violated the trust and safety of Hennepin County residents, the response cannot be silence or delay. The law must apply equally to everyone, including federal agents. I will continue these prosecutions carefully, fairly, and independently, with the seriousness these cases demand and the transparency our community deserves.”",
    quizResponse2: "1 |",
    quizResponse3:
      "1 | “Ordinarily, we would expect the federal government to be a partner in holding federal officers accountable. But when the federal government itself sent agents into our community and violence followed, Hennepin County obviously cannot wait for this corrupt, lawless administration to police itself. The county attorney’s office is responsible for prosecuting crimes committed here, no matter who commits them. If federal officers break Minnesota law in Hennepin County, the county attorney has not only the authority but the duty to act.”",
    quizResponse4:
      "1 | “Yes. Accountability is essential whenever government power is used, and it is also essential to building the public trust that real public safety requires. The county attorney’s office must gather evidence and victim accounts about the conduct of local law enforcement during Operation Metro Surge and bring charges when the law and facts support them. The law must be enforced equally—whether the defendant is on a street corner, in a boardroom, or wearing a badge.”",
    quizResponse5:
      "2 | “Young people deserve a real chance to change, and our system should be built around helping them do that whenever possible. For most juveniles, that means rehabilitation, diversion, treatment, education, and support—not prison. The data show that deferred prosecution can reduce recidivism compared to traditional prosecution, and we should follow that evidence. But we also have to be honest about repeat harm. A second chance does not mean turning a blind eye to violence, escalating behavior, or serial offending. The goal should be accountability that helps kids change while protecting the public.”",
    quizResponse6:
      "3 | “I believe in a case-by-case approach because with young people, the just outcome is often also the safest outcome. Research shows that incarcerating youth often does not reduce reoffending and can make future harm more likely, while well-run community-based supervision and services can produce better public safety outcomes. That is safety and justice working together, not competing. But serious violence requires serious scrutiny. For the most dangerous cases, secure or highly structured placement may be necessary. The public should not shoulder preventable risk, but neither should we ignore what actually reduces future crime.”",
    quizResponse7:
      "3 | “The county attorney’s office must work closely with local law enforcement to build strong cases, prioritize serious crime, and protect public safety. But partnership cannot mean capture. The office also has an independent duty to ensure that investigations are lawful, evidence is reliable, and officers are held accountable when they abuse their authority. Public safety depends on trust, and trust requires both collaboration with law enforcement and a clear checks-and-balances role for the county attorney.”",
    quizResponse8:
      "3 | “I would continue the core policy but change how it is implemented. Low-level, pretextual traffic stops have contributed to racial disparities and often do little to improve public safety. But reform only works if the public understands that serious crimes—illegal guns, drug trafficking, dangerous driving, violence, and other real public-safety threats—will still be prosecuted when the facts and law support it. I would also build this policy with law enforcement, not against them. The county attorney cannot command every local department’s traffic practices, so reducing disparities requires a coalition, clear standards, data, and shared priorities—not an announcement that leaves partners and the public uncertain.”",
    quizResponse9:
      "1 | “The governor was right to intervene in this case. That kind of intervention should be rare, but this was one of the clearest examples of how the office lost public trust and alienated people who should have been allies in reform. The controversy became a distraction from the data-driven, popular reforms that can make our system both fairer and safer. Reform requires judgment, communication, and coalition-building. When those break down in a serious case, state intervention may be necessary to restore confidence in the system.”",
    quizResponse10:
      "2 | “In this specific case, I would have prosecuted the two teenagers as adults and sought prison sentences from the beginning. That does not mean every juvenile case should be handled that way. Young people are different from adults, and rehabilitation should remain central in most cases. But serious violence requires serious, individualized judgment. In a case involving murder, the office needed to show victims’ families and the community that accountability, public safety, and reform can exist together. The failure to do that helped shatter trust in the office.”",
    quizResponse11:
      "1 | “I would continue and strengthen the partnership. An Attorney General like Keith Ellison is an asset to Hennepin County, and the county attorney should partner with the state’s top prosecutor wherever that collaboration helps protect residents, defend rights, and hold powerful interests accountable. That includes matters involving the federal government, consumer protection, civil rights, fraud, public corruption, and complex cases where shared expertise can make the work stronger. The county attorney must remain focussed on protecting the people of Hennepin County, but partnership between aligned offices is a strength.”",
  },
  candidateFrazier: {
    name: "Cedrick Frazier",
    website: "https://www.cedrickfrazier.org/",
    city: "New Hope",
    occupation:
      "DFL Minnesota State Legislator and Labor Attorney at Education Minnesota",
    age: "47",
    bio: "DFL Rep. Cedrick Frazier grew up on the South Side of Chicago in the Inglewood neighborhood, where he saw violence caused by the crack epidemic of the 1980s and 1990s. He moved to Minnesota in 1997 to attend the University of Minnesota-Morris in central Minnesota, moved to Mankato for graduate school at Minnesota State University, then attended the Mitchell Hamline School of Law in St. Paul.{newParagraph}Frazier worked as a public defender in Hennepin County under then-Chief Public Defender Mary Moriarty, who now serves as Hennepin County attorney. He was then hired by Minneapolis Public Schools as its director of equity and diversity, where he investigated employment harassment and discrimination cases. He joined the district's general counsel office, where he oversaw litigation for the entire district and responded to complaints.{newParagraph}He now works as a staff attorney for Education Minnesota, the state teachers’ union, where he’s been for 10 years. {newParagraph}Frazier was elected to the New Hope City Council in 2018, and as a state representative two years later. At the Legislature, Frazier served as vice chair of the Public Safety and Judiciary Committees, where he spearheaded several pieces of legislation that included voting rights expansion and investments in violence prevention, which both passed.{newParagraph}Frazier won the DFL endorsement earlier this month for the county attorney race. He is also endorsed by Minnesota Attorney General Keith Ellison, U.S. Senator Tina Smith, Lieutenant Governor and U.S. Senate hopeful Peggy Flanagan, Congresswoman Ilhan Omar and 22 of his colleagues in the Legislature, as well as several local officials.{newParagraph}Sahan Journal asked the county attorney candidates several questions about why they’re running for the office, and their priorities for the post. Read Frazier’s responses in his own words below.",
    quote1:
      "As the only DFL & Labor endorsed candidate in this race, I believe the decision before us this year is not simply about who holds the office of county attorney — it’s about whether we move forward, applying the lessons we’ve learned from the past, or regress to the old failed approaches that do not deliver the safety or fairness our communities deserve.{newParagraph}I grew up in a low-income neighborhood on the South Side of Chicago — a place very different from my home in New Hope, where my wife and I raise our daughters today. The community I grew up in faced gang violence, drug trafficking, and a legal system that too often failed the very people it claimed to serve. I lost loved ones to gun violence and watched neighbors become trapped in cycles of incarceration.{newParagraph}My lived experience, combined with my professional legal experience as a public defender in Hennepin County, legal counsel for Minneapolis Public Schools, and now a labor attorney at Education Minnesota, as well as my elected experience as a suburban city councilmember and state legislator, gives me the well-rounded perspective necessary to lead this office.{newParagraph}We are witnessing [President] Donald Trump destroy public trust in our legal system, using it for personal and political gain while eroding accountability at the highest levels. This is not public safety — it is federal overreach with deadly consequences. As the next county attorney, I will prosecute Trump’s federal agents who have violated Minnesota law.{newParagraph}The next Hennepin County attorney must prosecute violent crime to protect victims and reduce threats to public safety. But true public safety requires more than prosecution alone. My administration will also uphold workers’ rights, defend abortion access, and safeguard our environment. We will support survivors of domestic violence and sexual assault, and we will protect immigrant communities from unjust deportations.{newParagraph}We can build a legal system in Hennepin County that protects our communities, strengthens public trust, listens to those most impacted by crime, and ensures the rule of law is applied fairly to everyone. This will require strong, visionary, and steady political leadership from the Hennepin County attorney. That is precisely the leadership that I offer.",
    quote2:
      "Voters deserve a county attorney who understands what is at stake in this moment. Donald Trump is attacking our democratic institutions and is destroying the rule of law.{newParagraph}I am the only candidate in this race endorsed by the Minnesota DFL and the only candidate endorsed by labor unions. I have earned more endorsements from suburban mayors than all of my opponents combined. I am also the only candidate endorsed by [Hennepin] County commissioners, who I will work alongside to pass a $90+ million annual budget for the office.{newParagraph}These endorsements reflect a broad coalition united around a shared set of values.{newParagraph}Those values mean that no one is above the law, whether on the corner of the block or in the corner office. They mean treating wage theft as the serious crime it is, investing in proven violence prevention strategies, centering victims and survivors, and standing up to unlawful actions by ICE.{newParagraph}If we treat the Hennepin County Attorney’s Office as “business as usual,” we miss the opportunity — and the responsibility — to use this office to protect communities, defend rights, and respond to threats against our democracy.{newParagraph}Minnesotans are ready for a path forward where nobody is above the law, and nobody is beneath the protections of the law. My priorities as the next county attorney include:{newParagraph}- Building trust through transparency{newParagraph}- Centering victims and survivors{newParagraph}- Combating wage theft and fraud{newParagraph}- Confronting fentanyl and expanding pathways to recovery{newParagraph}- Defending democracy{newParagraph}- Disrupting gun violence with urgency and precision{newParagraph}- Ending cycles of domestic violence{newParagraph}- Ensuring youth accountability{newParagraph}- Strengthening integrity and ethical governance{newParagraph}- Partnering effectively with local law enforcement agencies{newParagraph}- Protecting immigrant communities from unjust deportations{newParagraph}- Reviewing wrongful convictions{newParagraph}- Safeguarding access to abortion and reproductive healthcare{newParagraph}- Standing up to Trump{newParagraph}- Supporting ambitious climate action, affordable housing, and health care access{newParagraph}- Improving transit safety{newParagraph}- Uniting against hate crimes and political violence{newParagraph}Please visit https://www.cedrickfrazier.org/priorities to learn more and offer your feedback.",
    quote3:
      "What really differentiates me from my predecessor and all of my opponents in this race is that I did not first learn about victims of crime from news stories, an academic textbook, or a case file on my desk. I grew up in a community impacted by gang violence and drug trafficking. I know what it is like to lose loved ones to gun violence.{newParagraph}My predecessor and I share a similar commitment to building a more equitable legal system. But how we get there matters. My leadership has been, and will be, defined by collaboration, accountability, and a clear focus on delivering lasting results.{newParagraph}During my service as a New Hope City Councilmember and state legislator, I have built strong relationships with community leaders, law enforcement, legislators, and mayors. These partnerships are essential to effectively leading the Hennepin County Attorney’s Office and advancing meaningful change.{newParagraph}Coalition building has been a central part of my work as an elected official. I am proud to have earned more endorsements than all of my opponents combined, including the sole endorsement of Minnesota Attorney General Keith Ellison. Our countywide coalition includes labor unions, community organizations, and a broad group of local elected leaders representing 39 different cities across Hennepin County. This coalition won't just help me win this race, but will also help me govern effectively.",
    quote4:
      "I grew up in a low income working class community. The failed Reagan era policies of the 1980s took a devastating toll on communities like the one I called home.{newParagraph}I understand what it is like to lose a loved one to drug addiction, to survive gun violence, and to be stopped by police without cause. As a teenager, I was shot at simply for wearing the wrong NFL jersey on the wrong block. I understand these experiences not because I have read about them in a book or read them in a case file on my desk, but because I have lived them.{newParagraph}People living in communities affected by violence do not want less safety. They want more safety. They want safety that works. They want decisions to be made with them, not for them. I understand that because I have lived it, and I will bring to this office a perspective and lived experience unlike any county attorney who has served before.{newParagraph}The county attorney’s office decisions have profound consequences for marginalized communities. When policies only prioritize incarceration over community based diversion programs or impose severe penalties for low level or ambiguous conduct, they deepen existing racial and economic disparities. Even policies that appear “neutral”, such as mandatory minimum sentences, can worsen inequities when they fail to account for the social, historical, and economic realities that shape people's lives.{newParagraph}I believe in accountability for harm, including incarceration when necessary to protect public safety. At the same time, I strongly oppose mandatory minimum sentences that strip judges and prosecutors of the ability to consider individual circumstances. Criminal justice decisions should be guided by proportionality and context, not rigid formulas that leave no room for common sense or humanity.{newParagraph}A powerful example of the harm caused by mandatory sentencing is the 2023 case of Steven Cooper in St. Louis County. Cooper, a Black man with a prior felony conviction, discovered a firearm among the belongings of his recently deceased brother. Knowing that he was legally prohibited from possessing a firearm, he wrapped the gun and contacted his parole officer because he intended to turn it in. He believed he was acting responsibly and in the interest of public safety.{newParagraph}Instead of being commended for doing the right thing, Cooper was arrested and charged with felony possession of a firearm, an offense carrying a mandatory prison sentence. The Duluth chapter of the NAACP, along with civil rights advocates and gun rights organizations, publicly called on the St. Louis County Attorney's Office to dismiss the charges.{newParagraph}This case, in which a man faced a mandatory sentence for attempting to turn a firearm over to authorities, illustrates why prosecutors and judges must have the discretion to consider context.",
    quote5:
      "The civil division of the county attorney’s office has traditionally focused on minimizing risk for county departments. Going forward, I believe it should also serve to protect our community and uphold justice in the face of political attacks. In an era of federal overreach and punitive actions against Minnesota and Hennepin County, our civil division must be fully engaged in defending the local interests of our residents. I will ensure that the division collaborates with counterparts in other jurisdictions across the country facing similar challenges, enabling coordinated litigation strategies and shared resources to effectively respond to these federal threats.{newParagraph}The Trump administration has targeted many programs that Hennepin County residents rely on every day — from health care to affordable housing to basic human services. They have made it clear that residents cannot access these longstanding programs unless the County complies with unjust immigration enforcement, persecutes our LGBTQ neighbors, and submits to their inhumane political agenda. As county attorney, I will stand up to these attacks by taking legal action when necessary and fighting to ensure that residents can access essential county services without being forced to accommodate their radical federal mandates.",
    quizResponse1:
      "1 | “I was the first candidate to publicly release a plan to prosecute ICE. I believe that no one is above the law, not Donald Trump and not his federal agents, and that no one in our community is beneath its protection.{newParagraph}This year, voters will decide what kind of leadership they want for Hennepin County: leadership with the courage to stand up when it matters most, or leadership that will bend to political pressure and allow the Trump administration to erode our rights, dignity, and safety. I am the only candidate in this race with a demonstrated record of standing up to Trump. I believe I am the candidate voters can trust to follow through on a promise to fight federal overreach and defend our community.”",
    quizResponse2:
      "1 | “I have been, and continue to be, the candidate who has spoken most clearly about this issue: I will prosecute ICE agents who violate Minnesota law.{newParagraph}I did not need political consultants or polling data to reach that position. I stood alongside our community, protesting in the streets after Renée and Alex were killed, and I have been consistent in demanding accountability ever since.{newParagraph}I am prepared to work closely with Attorney General Keith Ellison to deliver justice for Minnesota.{newParagraph}Please visit cedrickfrazier.org/accountability to see how I’ll get it done.”",
    quizResponse3:
      "1 | “From the beginning I’ve been clear: federal agents do not have absolute immunity, regardless of what [Vice President] JD Vance has claimed. When federal agents commit crimes in our county, the Hennepin County Attorney has both the authority and the responsibility to investigate and prosecute them.{newParagraph}Our retiring county attorney has established an important model of federal accountability through a formal partnership with the Minnesota Bureau of Criminal Apprehension (BCA) and the Minnesota Attorney General’s Office to investigate and prosecute these cases.{newParagraph}I am the only candidate in this race who is endorsed by Attorney General Keith Ellison, and I am committed to continuing and strengthening this partnership as the next Hennepin county attorney.”",
    quizResponse4:
      "1 | “Making sure everyone is held accountable, including those in positions of power or authority, is essential to building and maintaining public trust in the justice system.{newParagraph}My administration will establish an independent Public Integrity Unit to investigate police use-of-force cases, public corruption, and civil rights violations with transparency and impartiality. They will be committed to ensuring that all charging decisions are grounded in evidence, the law, and the safety of the community—not political influence. Staffed by prosecutors with subject matter expertise, this new unit will make charging recommendations to me as the elected county attorney, who will retain final responsibility for all charging decisions.”",
    quizResponse5:
      "2 | “As a father, I firmly believe that it is the responsibility of adults to teach youth to understand that their actions have real-life consequences for themselves and others. This means accountability that is both swift, and smart.{newParagraph}Using my background in public education, I understand that intervention can begin long before a case is presented to the county attorney’s office. My strong partnerships with schools throughout the county come built-in, and I will rely on these relationships to focus on early interventions that support youth and their families, prevent repeat offenses, and avoid deeper involvement in the legal system. We will work with schools and families to make sure children attend school, are actively learning during the day, and are safe at home each night.”",
    quizResponse6:
      "3 | “I do not believe that placing children in adult prisons serves the long-term interests of public safety. There will, unfortunately, be cases where a young person commits conduct so serious that certification and a prison sentence are warranted.{newParagraph}If our goal is to reduce recidivism and support successful reintegration, we must also invest in appropriate rehabilitation and treatment options that address the underlying causes of harmful behavior while still recognizing the seriousness of the offense.{newParagraph}The Hennepin County Home School closed in 2021 because of declining enrollment, rising operational costs, and poor outcomes. It had served as the county’s secure residential treatment facility for youth involved in the juvenile justice system. Five years later, Hennepin County still lacks an effective alternative for young people who cannot safely remain at home or in the community for a period of time.{newParagraph}As county attorney, I will use my relationships at the state Capitol and with the [Hennepin] County commissioners to advocate for the resources needed to establish secure residential treatment options in Hennepin County for youth who are not safe at home or in the community. These programs can provide the structure, treatment, and accountability necessary to help young people change course while protecting public safety.{newParagraph}Together, these efforts will promote accountability, expand opportunity, and strengthen long term public safety throughout Hennepin County.”",
    quizResponse7:
      "3 | “As county attorney, I will maintain collaborative relationships with local law enforcement and ensure that investigations focus on the evidence needed for attorneys to build strong cases in court. When cases go to trial, we need convictions to stick.{newParagraph}Failing to follow proper procedures during law enforcement searches leads to cases being tossed out. My administration will partner with law enforcement to ensure that these procedures are followed so that people who commit crimes can be held accountable. By communicating effectively, we can speed up the legal process for victims, protect defendants’ rights, and develop coordinated public safety strategies.”",
    quizResponse8:
      "3 | “I co-authored a bill to address this issue at the state level, but unfortunately it was blocked by Senate Republicans during end-of-session negotiations. This policy should be established in state law so it does not vary from city to city or county to county.{newParagraph}That being said, we also need to ensure that community members and other justice system partners are meaningfully engaged in all stages of policy development. No policy changes should come as a surprise to the people it impacts.{newParagraph}The Minneapolis Police Department has already committed to this policy change as part of their consent decree, and it has been a policy across the river in Ramsey County for years now. I believe there is a path forward to finding more common ground with system partners and advancing a workable, consistent policy that everyone can get behind.”",
    quizResponse9:
      "4 | “I believe elected leaders should have worked behind the scenes to prioritize public safety and the well-being of the family of Zaria McKeever. Regardless of my opinions on the case, I do not think it should be common practice for the governor to reassign criminal cases because they disagree with a charging decision. The governor would not have access to all of the evidence and facts available to a county attorney. Local communities across Minnesota elect their county attorneys to make difficult decisions, and if the public disagrees with those choices, they have the ability to vote them out of office.”",
    quizResponse10:
      "2 | “I believe the attorney general’s ultimate disposition in the case was appropriate. As a survivor of gun violence, I understand what it feels like to believe the system is not protecting you or the people you love. I will bring that lived experience and perspective to this role.{newParagraph}At the same time, I do not believe that placing children in adult prisons serves the long-term interests of public safety. If our goal is to reduce recidivism and support successful reintegration, we must also invest in appropriate rehabilitation and treatment options that address the underlying causes of harmful behavior while still recognizing the seriousness of the offense.”",
    quizResponse11:
      "1 | “I am the only candidate in this race endorsed by Attorney General Keith Ellison, reflecting his confidence in my ability to serve as a strong and effective partner. Together, AG Ellison and I will bring a level of coordination between our offices that strengthens our work on critical cases involving federal agents.{newParagraph}Our strong partnership will help ensure accountability, defend constitutional rights, protect consumers, and advance justice and public safety for all.”",
  },
};
